#!/usr/bin/env bash
#
# sgrm: simple-grm
#
# Requirements: grm, entr, go-list
#
# Installation:
#
# 	curl https://raw.githubusercontent.com/bom-d-van/bin/master/grm >> $GOPATH/bin/grm
# 	chmod +x $GOPATH/bin/grm
# 	curl https://raw.githubusercontent.com/bom-d-van/bin/master/sgrm >> $GOPATH/bin/sgrm
# 	chmod +x $GOPATH/bin/sgrm
#

FILES=()

for file in `go list -f '{{.Imports}}' ./... | tr -d '[]' | tr ' ' '\n' | sort | uniq`; do
	if [ -d "$GOPATH/src/$file" ]; then
		FILES+=("$GOPATH/src/$file")
	fi
done

find . ${FILES[@]} -iname '*.go' | entr -dr grm
